/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      screens: {
        xss: '375px',
      },
      colors: {
        'border-mobile': '#D9D9D9',
        'btn-order': '#fcaf17',
        'hover-btn-order': '#BD8311',
        'bg-cart': '#f9f9f9',
        'name-product': '#333f48',
        'root-price': '#fdaa63',
        'border-product-page': '#c8c7cc',
        'border-checkout': '#545454',
        'bg-checkout': '#e7e8fc',
        'border-layout-cart': '#e8e8e8',
        'bg-layout-profile': '#f8f8f8',
        'item-profile': '#FEEEEA',
        'option-filter': '#63b1bc',
        'border-variant': '#d2d1d4',
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
      },
      width: {
        45: '45rem',
        1000: '1000px',
      },
      minWidth: {
        '40px': '40px',
      },
      height: {
        700: '700px',
      },
      fontFamily: {
        body: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'system-ui',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'Noto Sans',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
          'Noto Color Emoji',
        ],
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'system-ui',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'Noto Sans',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
          'Noto Color Emoji',
        ],
      },
    },
  },
  plugins: [require('@tailwindcss/line-clamp')],
};
